# This makefile only performs the function of un-installing any
# potentials that may have been installed by running the sample
# makefiles in 'make install' mode.
#
# To run it, type
#
#   make clean

# This should be root directory of a7.3.3 package:
ROOT= ../..

POT=  ${ROOT}/Pot

default:

clean:
	rm ${ROOT}/Pot/000*
