       SUBROUTINE ZEDATE(BDATE)
C
C   GETS THE DATE (DAY-MONTH-YEAR)
C   Sun version
C
       CHARACTER*10 BDATE
       INTEGER LOCTIM(3)
       INTEGER LYEAR
       CHARACTER*3 MONTH(12)
       CHARACTER*1 DASH
       DATA DASH/'-'/
       DATA MONTH/'JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP',
     2            'OCT','NOV','DEC'/
       CALL IDATE(LOCTIM)
       LYEAR = LOCTIM(3) - (LOCTIM(3)/100)*100
       WRITE(BDATE,100) LOCTIM(1),DASH,MONTH(LOCTIM(2)),DASH,LYEAR
 100   FORMAT(I2,A1,A3,A1,I2,' ')
       RETURN
       END
C
       SUBROUTINE ZESEC(TBACK)
C
C   GETS CPU TIME IN SECONDS
C   Sun version
C
       REAL TARRAY(2)
       DOUBLE PRECISION TBACK
       T=ETIME(TARRAY)
       T=TARRAY(1)
       TBACK=T
       RETURN
       END
